# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

# Oracle DB Language Set
NLS_LANG: AMERICAN_AMERICA.AL32UTF8
BOND_WERKS: 381A
BOND_BUKRS: L300
CONNR: E52070000001
BNAREA: 5207
BUKRS: L300
MANDT: 168

#development:
#  MANDT: 168
#  FAILURE_LEVELS: CRITICAL,MAJOR,MINOR
#  QC_PLACE: IQC,IPQC,OQC,CUSTOMER
#  WERKS: 101A,281A,381A,382A,481A,482A,921A
#  WAERS: RMB,USD,HKD
#  VTWEG: DT,TX,PH
#  VTWEG_TX: 381A,382A,281A
#  VTWEG_DT: 481A,482A
#  VTWEG_PH: 111A,112A
#  PLANT_NO: LEI-4,LEI-6
#  UPLOAD_PATH: /tmp/upload
#  UPLOAD_LIMIT: 5
#  SERVER_URL: http://172.31.4.220:3158/
#  ZQM_ADMIN: 'lum.cl@l-e-i.com'
#  TV_PAGESIZE: 15
#  TV_PAGESIZE_MSG: 12
#  SRO_HOST: leisql
#  SRO_USERNAME: txreader
#  SRO_PASSWORD: txreader
#  SRO_DATABASE: SRO
#
#production:
#  MANDT: 168
#  FAILURE_LEVELS: CRITICAL,MAJOR,MINOR
#  QC_PLACE: IQC,IPQC,OQC,CUSTOMER
#  WERKS: 101A,281A,381A,382A,481A,482A,921A
#  WAERS: RMB,USD,HKD
#  VTWEG: DT,TX,PH
#  VTWEG_TX: 381A,382A,281A
#  VTWEG_DT: 481A,482A
#  VTWEG_PH: 111A,112A
#  PLANT_NO: LEI-4,LEI-6
#  UPLOAD_PATH: /tmp/upload
#  UPLOAD_LIMIT: 5
#  SERVER_URL: http://172.31.4.220:3158/
#  ZQM_ADMIN: 'lum.cl@l-e-i.com'
#  TV_PAGESIZE: 15
#  TV_PAGESIZE_MSG: 12
#  SRO_HOST: leisql
#  SRO_USERNAME: txreader
#  SRO_PASSWORD: txreader
#  SRO_DATABASE: SRO